version: '3.8' 
services:
  sqlite:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    restart: always
    tty: true
    volumes:
      - ./db/:/root/db/
    ports:
      - 3306:3306
volumes:
  postgres:
    driver: local
