version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
